language: php

# As of May 2019, Travis is phasing out VMs based on Precise, which means that we can only test on php >= 5.6 going forward...
dist: xenial

php:
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  # This is mandatory or the 'apt-get install' calls following will fail
  - sudo apt-get update -qq
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo apt-get install -y privoxy

  # Disable xdebug for speed (executing composer), but allow us to re-enable it later
  - export XDEBUG_INI=`php -i | grep xdebug.ini | grep home/travis | grep -v '=>' | head -1`
  - export XDEBUG_INI=${XDEBUG_INI/,/}
  - if [ "$XDEBUG_INI" != "" ]; then mv "$XDEBUG_INI" "$XDEBUG_INI.bak"; fi

install:
  - composer install

  # Re-enable xdebug for when we need to generate code coverage
  - export COVERAGE_OPTS=""
  - if [ "$TRAVIS_PHP_VERSION" = "7.3" -a "$XDEBUG_INI" != "" ]; then mv "$XDEBUG_INI.bak" "$XDEBUG_INI" && export COVERAGE_OPTS="--coverage-clover=coverage.clover"; fi

before_script:
  # Set up Apache and Privoxy instances inside the Travis VM and use them for testing against
  - ./tests/ci/travis/setup_php_fpm.sh
  - ./tests/ci/travis/setup_apache.sh
  - ./tests/ci/travis/setup_privoxy.sh

  # output what version of phpunit we got going
  - vendor/bin/phpunit --version

script:
  # Travis currently compiles PHP with an oldish cURL/GnuTLS combination;
  # to make the tests pass when Apache has a bogus SSL cert whe need the full set of options below
  vendor/bin/phpunit $COVERAGE_OPTS tests LOCALSERVER=localhost URI=/demo/server/server.php HTTPSSERVER=localhost HTTPSURI=/demo/server/server.php PROXY=localhost:8080 HTTPSVERIFYHOST=0 HTTPSIGNOREPEER=1 SSLVERSION=0 DEBUG=0

after_failure:
  # Save as much info as we can to help developers
  - cat apache_error.log
  - cat apache_access.log

after_script:
  # Upload code-coverage to Scrutinizer
  - if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  # Upload code-coverage CodeClimate
  - if [ -f coverage.clover ]; then CODECLIMATE_REPO_TOKEN=7fa6ee01e345090e059e5e42f3bfbcc8692feb8340396382dd76390a3019ac13 ./vendor/bin/test-reporter --coverage-report=coverage.clover; fi

# reduce depth (history) of git checkout
git:
    depth: 5
